name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc: ["8.10.2", "8.8.4", "8.6.5"]
        include:
          - os: macOS-latest
            ghc: "8.10.2"

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/cache@v2
        id: cache-cabal
        name: Cache dependencies
        with:
          path: |
            ~/.cabal/config
            ~/.cabal/packages/hackage.haskell.org/
            ~/.cabal/store
          key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-${{ hashFiles('cabal.project') }}
          restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-cabal-

      - uses: actions/cache@v2
        name: Cache build
        with:
          path: dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-dist-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-dist-

      - name: Add non-system GHC to path
        if: ${{ runner.os }} == 'ubuntu-latest'
        run: echo "/opt/ghc/${{ matrix.ghc }}/bin" >> $GITHUB_PATH

      - name: cabal update
        if: steps.cache-cabal.outputs.cache-hit != 'true'
        run: cabal update

      - name: Build library
        run: cabal build ki:lib:ki --disable-optimization

      - name: Build unit tests
        run: cabal build ki:test:unit-tests --disable-optimization

      - name: Run unit tests
        run: cabal run ki:test:unit-tests --disable-optimization

      - name: Build library with 'test' flag
        run: cabal build ki:lib:ki --constraint "ki +test" --disable-optimization

      - name: Build dejafu tests
        run: cabal build ki:test:dejafu-tests --constraint "ki +test" --disable-optimization

      - name: Run dejafu tests
        run: cabal run ki:test:dejafu-tests --constraint "ki +test" --disable-optimization
