name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc: ["8.10.2", "8.8.4", "8.6.5"]
        include:
          - os: macOS-latest
            ghc: "8.10.2"

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/cache@v2
        id: cache-cabal
        name: Cache dependencies
        with:
          path: |
            ~/.cabal/config
            ~/.cabal/packages/hackage.haskell.org/
            ~/.cabal/store
          key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-${{ hashFiles('cabal.project') }}
          restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-cabal-

      - uses: actions/cache@v2
        name: Cache build
        with:
          path: dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-dist-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-dist-

      - name: Set path
        run: |
          echo "::add-path::/opt/cabal/3.2/bin"
          echo "::add-path::/opt/ghc/${{ matrix.ghc }}/bin"

      - name: cabal update
        if: steps.cache-cabal.outputs.cache-hit != 'true'
        run: cabal update

      - name: Build
        run: cabal build ki:lib:ki --disable-optimization

      - name: Build tests
        run: cabal build ki:test:tests --constraint "ki +test" --disable-optimization --enable-tests

      - name: Run tests
        run: cabal run ki:test:tests --constraint "ki +test" --disable-optimization --enable-tests
